feat: add server variable extensions
pb33f/libopenapi pull request #326
Opened 2024-08-27 16:33 UTC by geffersonFerraz

Allow to use server variable extension:
```
	envVar := &v3.ServerVariable{
		Enum:       []string{"api.mycompany.com", "api-preprod.mycompany.com"},
		Extensions: orderedmap.New[string, *yaml.Node](),
	}
	envVar.Description = "Environment to use"
	envVar.Default = "api.mycompany.com"
	envTransforms := []map[string]interface{}{
		{
			"type": "translate",
			"translations": []map[string]string{
				{"from": "prod", "to": "api.mycompany.com"},
				{"from": "pre-prod", "to": "api-preprod.mycompany.com"},
			},
		},
	}
	envVar.Extensions.Set("x-transforms", createExtension(envTransforms))
	server.Variables.Set("env", envVar)

	mergedSpecA.Model.Servers = append(mergedSpecA.Model.Servers, server)
```

2024-08-27 19:28 UTC, daveshanley commented
Two lines to cover and it's good to go.

2024-08-28 16:32 UTC, geffersonFerraz commented on datamodel/low/v3/server_test.go
> +	assert.Equal(t, "true", variable_pair.Value.Value.Content[1].Value)
Thanks @daveshanley !
I did the best I could, but I think it looks ugly. However, it works.
If you have any tips for this part of the test, I'd be happy to study it and improve it.

2024-09-09 16:51 UTC, daveshanley commented
Fix the tests and I can add this in!

2024-09-11 15:10 UTC, daveshanley requested changes

2024-09-11 15:16 UTC, daveshanley approved these changes

2024-09-11 15:19 UTC, merged